### ISSUE TITLE
Update the "py38" version with latest fixes

### ISSUE THREAD

**Issue by ilyagr** [balki/vimtabdiff#7]
I'd like to see 512df2948e0008e9e1c6219ec3b1219377838a34 and da5e24260a60d65479b3d64c608b8b072f5bdf19 backported to the py3.8 version of vimtabdiff.

I wonder if you could change the tag "py38" to be a branch "py38" instead. Then, one of us can backport those commits, and I can keep sending PRs if any more critical fixes or features need to be backported.

I think backporting the two changes I mentioned above is plenty for now. The need for the first one is self-evident, while the second one is important for using `gvim --nofork` or forcing a color theme with readable diffs for older versions of vim (`vim -c 'colorscheme murphy'`  for Vim 8 and below).

I'm asking because I'd like to recommend that people use this with https://github.com/martinvonz/jj, but I'm worried a good number of people don't have Python 3.10 installed. For instance, one the machines I use is on Debian stable, and that is on Python 3.9. Python 3.8 is still supported until Oct 2024, and 3.9 is supported for another year after that (though it's quite likely that 3.10 will become ubiquitous significantly earlier).

**Comment by balki** [comment]
Glad to see this is useful for more users! Created new branch for py38 and backported those fixes. Please create PR against the branch if anyother commits worth backporting. Thanks!

https://github.com/balki/vimtabdiff/tree/br-py38

**Comment by ilyagr** [comment]
Thank you very much!
